"""
YOLOv8 fine-tuning trainer.

Fine-tunes YOLOv8n (nano) on the UC4 enemy dataset.  YOLOv8n is chosen for
its sub-5 ms TensorRT inference on high-end GPUs while retaining reasonable
detection quality.  If mAP proves insufficient, upgrade to yolov8s or yolov8m.

Usage:
    python -m training.trainer \
        --data dataset/yolo/data.yaml \
        --epochs 150 \
        --batch 16 \
        --imgsz 640 \
        --model yolov8n.pt \
        --output models/run1
"""

from __future__ import annotations

import argparse
from pathlib import Path


def train(
    data_yaml: str,
    base_model: str = "yolov8n.pt",
    epochs: int = 150,
    batch: int = 16,
    imgsz: int = 640,
    output_dir: str = "models/training",
    device: str = "0",
    workers: int = 8,
    patience: int = 30,
    augment: bool = True,
) -> Path:
    """
    Fine-tune YOLOv8 on the enemy dataset.

    Parameters
    ----------
    data_yaml   : path to data.yaml generated by dataset_pipeline.
    base_model  : Ultralytics model tag or path to a .pt checkpoint.
    epochs      : max training epochs.
    batch       : batch size (set to -1 for auto-batch).
    imgsz       : input resolution (should match inference input_size).
    output_dir  : parent dir for training runs.
    device      : CUDA device index string (e.g. "0") or "cpu".
    workers     : DataLoader workers.
    patience    : early-stop patience in epochs.
    augment     : enable Ultralytics built-in augmentation.

    Returns
    -------
    Path to the best weights (.pt).
    """
    from ultralytics import YOLO

    model = YOLO(base_model)

    results = model.train(
        data       = data_yaml,
        epochs     = epochs,
        batch      = batch,
        imgsz      = imgsz,
        project    = output_dir,
        name       = "enemy_detector",
        device     = device,
        workers    = workers,
        patience   = patience,
        augment    = augment,
        # Aggressive augmentation for combat game scenes
        hsv_h      = 0.015,
        hsv_s      = 0.7,
        hsv_v      = 0.4,
        flipud     = 0.0,    # People rarely appear upside-down
        fliplr     = 0.5,
        mosaic     = 1.0,
        mixup      = 0.1,
        copy_paste = 0.1,
        # Tuned for small-to-medium person bounding boxes
        degrees    = 5.0,
        translate  = 0.1,
        scale      = 0.5,
        shear      = 2.0,
        perspective= 0.0005,
        save_period= 10,
        # Training hyperparams
        lr0        = 0.01,
        lrf        = 0.001,
        momentum   = 0.937,
        weight_decay = 0.0005,
        warmup_epochs = 3,
        box        = 7.5,
        cls        = 0.5,
        dfl        = 1.5,
        verbose    = True,
    )

    best = Path(results.save_dir) / "weights" / "best.pt"
    print(f"\nTraining complete.")
    print(f"Best weights: {best}")
    print(f"mAP50: {results.results_dict.get('metrics/mAP50(B)', 'N/A'):.4f}")
    print(f"mAP50-95: {results.results_dict.get('metrics/mAP50-95(B)', 'N/A'):.4f}")
    return best


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(description="UC4 YOLOv8 Trainer")
    parser.add_argument("--data",    required=True,             help="Path to data.yaml")
    parser.add_argument("--model",   default="yolov8n.pt",      help="Base model")
    parser.add_argument("--epochs",  type=int,   default=150)
    parser.add_argument("--batch",   type=int,   default=16)
    parser.add_argument("--imgsz",   type=int,   default=640)
    parser.add_argument("--output",  default="models/training")
    parser.add_argument("--device",  default="0")
    parser.add_argument("--workers", type=int,   default=8)
    parser.add_argument("--patience",type=int,   default=30)
    args = parser.parse_args()

    train(
        data_yaml  = args.data,
        base_model = args.model,
        epochs     = args.epochs,
        batch      = args.batch,
        imgsz      = args.imgsz,
        output_dir = args.output,
        device     = args.device,
        workers    = args.workers,
        patience   = args.patience,
    )


if __name__ == "__main__":
    main()
